package com.cdk.ea.tools.data.generation.query;

import java.util.stream.IntStream;

import com.cdk.ea.tools.data.generation.generators.DataCollector;
import com.cdk.ea.tools.data.generation.generators.Generator;
import com.cdk.ea.tools.data.generation.types.Type;

import lombok.extern.slf4j.Slf4j;

/**
 * Runner class which is responsible to run a single {@link Query}
 * 
 * @author Sarvesh Dubey <sarvesh.dubey@cdk.com>
 * @since 10-02-2017
 * @version 1.0
 */
@Slf4j
public class QueryRunner {

    private final Query query;

    private QueryRunner(Query query) {
	this.query = query;
    }

    /**
     * Factory method to instantiate {@link QueryRunner}
     * 
     * @param queryParams
     *            from which the runner must be instantiated.
     * @return {@link QueryRunner}
     */
    @SuppressWarnings(value = { "all" })
    public static QueryRunner from(String... queryParams) {
	return new QueryRunner(new Query.QueryBuilder().build(queryParams));
    }

    /**
     * Runs the encapsulated {@link Query} and collects the data.
     * 
     * @return {@link DataCollector} containing the data generated by
     *         {@link Query}
     */
    public DataCollector run() {
	Type dataType = query.getTypeBuilder().buildType();
	Generator<?> generator = dataType.generator();
	DataCollector dataCollector = query.getDataCollector();
	log.debug("beginning to run query for type {} with collector name [{}] and data quantity [{}]", dataType,
		dataCollector.getName(), query.getQuantity());
	IntStream.rangeClosed(1, query.getQuantity()).forEach(i -> dataCollector.getData().add(generator.generate()));
	log.debug("query executed successfully");
	return dataCollector;
    }

}
